config/routes.rb
Rails.application.routes.draw do
  get '/wrm-dashboard(/:user_id)', to: 'water_rights_management#dashboard', as: :wrm_dashboard
  get '/show-water-rights', to: 'water_rights_management#show_water_rights', as: :show_water_rights
  get "/get-water-rights-data/:id(.:format)", to: "water_rights_management#get_data", as: :get_water_rights_data

  resources :water_rights
  resources :point_of_diversions
  resources :place_of_use_areas
  resources :for_sales
  resources :wanteds

  post '/place_of_use_area_water_rights(.:format)', to: 'place_of_use_area_water_rights#create', as: :place_of_use_area_water_rights
  delete '/place_of_use_area_water_rights(.:format)', to: 'place_of_use_area_water_rights#destroy', as: :place_of_use_area_water_right
  post '/point_of_diversion_water_rights(.:format)', to: 'point_of_diversion_water_rights#create', as: :point_of_diversion_water_rights
  delete '/point_of_diversion_water_rights(.:format)', to: 'point_of_diversion_water_rights#destroy', as: :point_of_diversion_water_right

  get "/listings-dashboard", to: "listings#dashboard", as: :listings_dashboard
  get "/buy-sell", to: "listings#buy_sell", as: :buy_sell
  get "/get-listings-data", to: "listings#get_data", as: :get_listings_data

  # get "/contact", to: "static_pages#contact", as: :contact

  resources :listing_areas

  devise_for :users

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/for_sale.rb
class ForSale < ApplicationRecord
  belongs_to :listing_area
  validates :description, :price, :listing_area, presence: true
end

app/controllers/for_sales_controller.rb
class ForSalesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_for_sale, only: [:show, :edit, :update, :destroy]

  # GET /for_sales
  def index
    @for_sales = ForSale.includes(:listing_area)
    authorize @for_sales
  end

  # GET /for_sales/1
  def show
    authorize @for_sale
  end

  # GET /for_sales/new
  def new
    @for_sale = ForSale.new
    authorize @for_sale
  end

  # GET /for_sales/1/edit
  def edit
    authorize @for_sale
  end

  # POST /for_sales
  def create
    @for_sale = ForSale.new(for_sale_params)
    authorize @for_sale

    if @for_sale.save
      redirect_to @for_sale, notice: 'For sale was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /for_sales/1
  def update
    authorize @for_sale
    if @for_sale.update(for_sale_params)
      redirect_to @for_sale, notice: 'For sale was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /for_sales/1
  def destroy
    authorize @for_sale
    @for_sale.destroy
    redirect_to listings_dashboard_url, notice: 'For sale was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_for_sale
      @for_sale = ForSale.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def for_sale_params
      params.require(:for_sale).permit(:volume, :source, :description, :price, :contact_info, :listing_area_id)
    end
end

app/views/for_sales/_for_sale.html.erb
<tr>
  <td><%= for_sale.description %></td>
  <td><%= for_sale.volume %></td>
  <td><%= for_sale.source %></td>
  <td><%= for_sale.price %></td>
  <td><%= for_sale.contact_info %></td>
  <td><%= for_sale.listing_area.name %></td>
  <td><%= link_to 'Show', for_sale %></td>
  <td><%= link_to 'Edit', edit_for_sale_path(for_sale) %></td>
  <td><%= link_to 'Destroy', for_sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/for_sales/_form.html.erb
<%= simple_form_for(@for_sale) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :volume %>
    <%= f.input :source %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :contact_info %>
    <%= f.association :listing_area %>
  </div>

  <div class="form-actions text-center">
    <% if @for_sale.new_record? %>
      <%= f.button :submit, "Create For Sale", class: "btn-block btn-lg" %>
    <% else %>
      <%= f.button :submit, "Update For Sale", class: "btn-block btn-lg" %>
    <% end %>
  </div>
<% end %>

app/views/for_sales/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
      <h2 class="text-center">Editing For Sale</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/for_sales/index.html.erb
<table id="for-sales-table" class="table table-striped table-bordered dt-responsive no-wrap" width="100%">
  <thead>
    <tr>
      <th>Description</th>
      <th>Volume</th>
      <th>Source</th>
      <th>Price</th>
      <th>Contact info</th>
      <th>Listing area</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render(@for_sales) %>
  </tbody>
</table>

<div class="text-center">
  <%= link_to 'New For Sale', new_for_sale_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/for_sales/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
      <h2 class="text-center">New For Sale</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/for_sales/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <p>
        <strong>Volume:</strong>
        <%= @for_sale.volume %> ac-ft
      </p>

      <p>
        <strong>Source:</strong>
        <%= @for_sale.source %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @for_sale.description %>
      </p>

      <p>
        <strong>Price:</strong>
        $<%= @for_sale.price %>/ac-ft
      </p>

      <p>
        <strong>Contact info:</strong>
        <%= @for_sale.contact_info %>
      </p>

      <p>
        <strong>Listing area:</strong>
        <%= @for_sale.listing_area.name %>
      </p>

      <%= link_to 'Edit', edit_for_sale_path(@for_sale) %>
    </div>
  </div>
</div>