config/routes.rb
Rails.application.routes.draw do
  get '/wrm-dashboard(/:user_id)', to: 'water_rights_management#dashboard', as: :wrm_dashboard
  get '/show-water-rights', to: 'water_rights_management#show_water_rights', as: :show_water_rights
  get "/get-water-rights-data/:id(.:format)", to: "water_rights_management#get_data", as: :get_water_rights_data

  resources :water_rights
  resources :point_of_diversions
  resources :place_of_use_areas
  resources :for_sales
  resources :wanteds

  post '/place_of_use_area_water_rights(.:format)', to: 'place_of_use_area_water_rights#create', as: :place_of_use_area_water_rights
  delete '/place_of_use_area_water_rights(.:format)', to: 'place_of_use_area_water_rights#destroy', as: :place_of_use_area_water_right
  post '/point_of_diversion_water_rights(.:format)', to: 'point_of_diversion_water_rights#create', as: :point_of_diversion_water_rights
  delete '/point_of_diversion_water_rights(.:format)', to: 'point_of_diversion_water_rights#destroy', as: :point_of_diversion_water_right

  get "/listings-dashboard", to: "listings#dashboard", as: :listings_dashboard
  get "/buy-sell", to: "listings#buy_sell", as: :buy_sell
  get "/get-listings-data", to: "listings#get_data", as: :get_listings_data

  # get "/contact", to: "static_pages#contact", as: :contact

  resources :listing_areas

  devise_for :users

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/listing_area.rb
class ListingArea < ApplicationRecord
  has_many :wanteds, dependent: :destroy
  has_many :for_sales, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_attached_file :kml, use_timestamp: false
  # validates_attachment_content_type :kml, content_type: "application/vnd.google-earth.kml+xml"
  validates_attachment_presence :kml
  validates_attachment_file_name :kml, matches: /kml\Z/
  after_save :queue_processing

private
  
  def queue_processing
    if saved_change_to_kml_updated_at?
      parser = KmlParser.new(id, 'ListingArea')
      parser.delay.parse_polygon
    end
  end
end

app/controllers/listing_areas_controller.rb
class ListingAreasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing_area, only: [:show, :edit, :update, :destroy]

  # GET /listing_areas
  def index
    @listing_areas = ListingArea.all
    authorize @listing_areas
  end

  # GET /listing_areas/1
  def show
    authorize @listing_area
  end

  # GET /listing_areas/new
  def new
    @listing_area = ListingArea.new
    authorize @listing_area
  end

  # GET /listing_areas/1/edit
  def edit
    authorize @listing_area
  end

  # POST /listing_areas
  def create
    @listing_area = ListingArea.new(listing_area_params)
    authorize @listing_area

    if @listing_area.save
      redirect_to @listing_area, notice: 'Listing area was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /listing_areas/1
  def update
    authorize @listing_area
    if @listing_area.update(listing_area_params)
      redirect_to @listing_area, notice: 'Listing area was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /listing_areas/1
  def destroy
    authorize @listing_area
    @listing_area.destroy
    redirect_to listings_dashboard_url, notice: 'Listing area was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing_area
      @listing_area = ListingArea.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def listing_area_params
      params.require(:listing_area).permit(:name, :policy, :kml)
    end
end

app/views/listing_areas/_form.html.erb
<%= simple_form_for @listing_area, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :policy %>
    <%= f.input :kml %>
    <% if @listing_area.kml_file_name %>
      <p>Current KML File: <%= @listing_area.kml_file_name %></p>
      <% if @listing_area.polygon %>
        <%= content_tag "div", id: "map_canvas", class: "edit_page", data: {feature: {type: "Feature", geometry: @listing_area.polygon}} do %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="form-actions text-center">
    <% if @listing_area.new_record? %>
      <%= f.button :submit, "Create Listing Area", class: "btn-block btn-lg" %>
    <% else %>
      <%= f.button :submit, "Update Listing Area", class: "btn-block btn-lg" %>
    <% end %>
  </div>
<% end %>

app/views/listing_areas/_listing_area.html.erb
<tr>
  <td><%= listing_area.name %></td>
  <td class="table-word-wrap"><%= listing_area.policy %></td>
  <td><%= static_map(listing_area.polygon) if listing_area.polygon %></td>
  <td><%= link_to 'Show', listing_area %></td>
  <td><%= link_to 'Edit', edit_listing_area_path(listing_area) %></td>
  <td><%= link_to 'Destroy', listing_area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/listing_areas/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
      <h2 class="text-center">Editing Listing Area</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/listing_areas/index.html.erb
<table id="listing-areas-table" class="table table-striped table-bordered dt-responsive no-wrap" width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Policy</th>
      <th>Preview Map</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render(@listing_areas) %>
  </tbody>
</table>

<div class="text-center">
  <%= link_to 'New Listing Area', new_listing_area_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/listing_areas/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
      <h2 class="text-center">New Listing Area</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/listing_areas/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <h2><%= @listing_area.name %> <%= link_to '(edit)', edit_listing_area_path(@listing_area), class: "edit-link" %></h2>

      <p class="table-word-wrap"><%= @listing_area.policy %></p>

      <% if @listing_area.polygon %>
        <%= content_tag "div", id: "map_canvas", class: "show_page", data: {feature: {type: "Feature", geometry: @listing_area.polygon}} do %>
        <% end %>
      <% end %>

      <p>
        Polygon: <%= truncate(@listing_area.polygon.to_s, length: 300) %>
      </p>
  
    </div>
  </div>
</div>