config/routes.rb
Rails.application.routes.draw do
  get '/wrm-dashboard(/:user_id)', to: 'water_rights_management#dashboard', as: :wrm_dashboard
  get '/show-water-rights', to: 'water_rights_management#show_water_rights', as: :show_water_rights
  get "/get-water-rights-data/:id(.:format)", to: "water_rights_management#get_data", as: :get_water_rights_data

  resources :water_rights
  resources :point_of_diversions
  resources :place_of_use_areas
  resources :for_sales
  resources :wanteds

  post '/place_of_use_area_water_rights(.:format)', to: 'place_of_use_area_water_rights#create', as: :place_of_use_area_water_rights
  delete '/place_of_use_area_water_rights(.:format)', to: 'place_of_use_area_water_rights#destroy', as: :place_of_use_area_water_right
  post '/point_of_diversion_water_rights(.:format)', to: 'point_of_diversion_water_rights#create', as: :point_of_diversion_water_rights
  delete '/point_of_diversion_water_rights(.:format)', to: 'point_of_diversion_water_rights#destroy', as: :point_of_diversion_water_right

  get "/listings-dashboard", to: "listings#dashboard", as: :listings_dashboard
  get "/buy-sell", to: "listings#buy_sell", as: :buy_sell
  get "/get-listings-data", to: "listings#get_data", as: :get_listings_data

  # get "/contact", to: "static_pages#contact", as: :contact

  resources :listing_areas

  devise_for :users

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/water_right.rb
class WaterRight < ApplicationRecord
  belongs_to :user, optional: true
  has_many :place_of_use_area_water_rights
  has_many :place_of_use_areas, through: :place_of_use_area_water_rights
  has_many :point_of_diversion_water_rights
  has_many :point_of_diversions, through: :point_of_diversion_water_rights
  validates :number, presence: true, uniqueness: true

# private
  
  def self.send_reminders(num_of_days)
    WaterRight.all.each do |water_right|
      if water_right.proof_due_date && (water_right.proof_due_date - num_of_days) == Date.today
        TransactionMailer.proof_due_date_reminder(water_right).deliver_now
      end
    end
  end
end

app/controllers/water_rights_controller.rb
class WaterRightsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_water_right, only: [:show, :edit, :update, :destroy]

  # GET /water_rights
  def index
    @water_rights = WaterRight.includes(:user)
    authorize @water_rights
  end

  # GET /water_rights/1
  def show
    authorize @water_right
    @unassociated_place_of_use_areas = PlaceOfUseArea.all - @water_right.place_of_use_areas
    @unassociated_point_of_diversions = PointOfDiversion.all - @water_right.point_of_diversions
  end

  # GET /water_rights/new
  def new
    @water_right = WaterRight.new
    authorize @water_right
  end

  # GET /water_rights/1/edit
  def edit
    authorize @water_right
  end

  # POST /water_rights
  def create
    @water_right = WaterRight.new(water_right_params)
    authorize @water_right

    if @water_right.save
      redirect_to @water_right, notice: 'Water right was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /water_rights/1
  def update
    authorize @water_right
    if @water_right.update(water_right_params)
      redirect_to @water_right, notice: 'Water right was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /water_rights/1
  def destroy
    authorize @water_right
    @water_right.destroy
    redirect_to wrm_dashboard_url, notice: 'Water right was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_water_right
      @water_right = WaterRight.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def water_right_params
      params.require(:water_right).permit(:number, :flow_cfs, :flow_ac_ft, :uses, :change_application_number, :proof_due_date, :user_id, :priority_date, :comments, :external_link, :view_link_text)
    end
end

app/views/water_rights/_form.html.erb
<%= simple_form_for(@water_right) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.input :flow_cfs %>
    <%= f.input :flow_ac_ft %>
    <%= f.input :uses %>
    <%= f.input :change_application_number %>
    <%= f.input :proof_due_date, start_year: 1880, end_year: Date.today.year + 15, include_blank: true %>
    <%= f.input :priority_date, start_year: 1880, end_year: Date.today.year + 15, include_blank: true %>
    <%= f.input :view_link_text %>
    <%= f.input :external_link %>
    <%= f.input :comments %>
    <%= f.association :user, label_method: :email %>
  </div>

  <div class="form-actions text-center">
    <% if @water_right.new_record? %>
      <%= f.button :submit, "Create Water Right", class: "btn-block btn-lg" %>
    <% else %>
      <%= f.button :submit, "Update Water Right", class: "btn-block btn-lg" %>
    <% end %>
  </div>
<% end %>

app/views/water_rights/_water_right.html.erb
<tr>
  <td><%= water_right.number %></td>
  <td><%= water_right.flow_cfs %></td>
  <td><%= water_right.flow_ac_ft %></td>
  <td><%= water_right.uses %></td>
  <td><%= water_right.change_application_number %></td>
  <td><%= water_right.proof_due_date %></td>
  <td><%= water_right.priority_date %></td>
  <td><%= water_right.view_link_text %></td>
  <td class="table-word-wrap"><%= link_to water_right.external_link, water_right.external_link if water_right.external_link %></td>
  <td><%= water_right.user.email if water_right.user %></td>
  <td><%= water_right.comments %></td>
  <td><%= link_to 'Show', water_right %></td>
  <td><%= link_to 'Edit', edit_water_right_path(water_right) %></td>
  <td><%= link_to 'Destroy', water_right, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/water_rights/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
      <h2 class="text-center">Editing Water Right</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/water_rights/index.html.erb
<table id="water-rights-table" class="table table-striped table-bordered dt-responsive no-wrap" width="100%">
  <% if @water_rights.any? %>
    <thead>
      <tr>
        <th>Number</th>
        <th>Flow cfs</th>
        <th>Flow ac ft</th>
        <th>Uses</th>
        <th>Change application number</th>
        <th>Proof due date</th>
        <th>Priority date</th>
        <th>View link text</th>
        <th>External link</th>
        <th>User</th>
        <th>Comments</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  <% end %>
  <tbody>
    <%= render(@water_rights) %>
  </tbody>
</table>

<div class="text-center">
  <%= link_to 'New Water Right', new_water_right_path, class: 'btn btn-primary btn-lg' %>
</div>

app/views/water_rights/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
      <h2 class="text-center">New Water Right</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/water_rights/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <p>
        <strong>Number:</strong>
        <%= @water_right.number %>
      </p>

      <p>
        <strong>Flow cfs:</strong>
        <%= @water_right.flow_cfs %>
      </p>

      <p>
        <strong>Flow ac ft:</strong>
        <%= @water_right.flow_ac_ft %>
      </p>

      <p>
        <strong>Uses:</strong>
        <%= @water_right.uses %>
      </p>

      <p>
        <strong>Change application number:</strong>
        <%= @water_right.change_application_number %>
      </p>

      <p>
        <strong>Proof due date:</strong>
        <%= @water_right.proof_due_date %>
      </p>

      <p>
        <strong>Priority date:</strong>
        <%= @water_right.priority_date %>
      </p>

      <p>
        <strong>View link text:</strong>
        <%= @water_right.view_link_text %>
      </p>

      <p class="table-word-wrap">
        <strong>External link:</strong>
        <%= link_to @water_right.external_link, @water_right.external_link if @water_right.external_link %>
      </p>

      <p>
        <strong>User:</strong>
        <%= @water_right.user.email if @water_right.user %>
      </p>

      <% if @water_right.comments %>
        <p>
          <strong>Comments:</strong>
          <%= @water_right.comments %>
        </p>
      <% end %>

      <div>
        <strong>Place of Use Areas:</strong>
        <ul>
          <% @water_right.place_of_use_areas.each do |area| %>
            <li><%= area.name %> <%= link_to '(x)', place_of_use_area_water_right_path(water_right_id: @water_right.id, place_of_use_area_id: area.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
          <% end %>
        </ul>
        <%= simple_form_for :place_of_use_area_water_right, url: '/place_of_use_area_water_rights' do |f| %>
          <%= f.input :water_right_id, as: :hidden, input_html: { value: @water_right.id } %>
          <%= f.input :place_of_use_area_id, collection: @unassociated_place_of_use_areas, label_method: :name, value_method: :id, label: false, include_blank: false %>
          <%= f.submit "Create Association", class: 'btn btn-primary' %>
        <% end %>
      </div>


      <div>
        <strong>Points of Diversion:</strong>
        <ul>
          <% @water_right.point_of_diversions.each do |point| %>
            <li><%= point.name %> <%= link_to '(x)', point_of_diversion_water_right_path(water_right_id: @water_right.id, point_of_diversion_id: point.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
          <% end %>
        </ul>
        <%= simple_form_for :point_of_diversion_water_right, url: '/point_of_diversion_water_rights' do |f| %>
          <%= f.input :water_right_id, as: :hidden, input_html: { value: @water_right.id } %>
          <%= f.input :point_of_diversion_id, collection: @unassociated_point_of_diversions, label_method: :name, value_method: :id, label: false, include_blank: false %>
          <%= f.submit "Create Association", class: 'btn btn-primary' %>
        <% end %>
      </div>


      <%= link_to 'Edit', edit_water_right_path(@water_right) %>
    </div>
  </div>
</div>