config/routes.rb
Rails.application.routes.draw do
  get '/wrm-dashboard(/:user_id)', to: 'water_rights_management#dashboard', as: :wrm_dashboard
  get '/show-water-rights', to: 'water_rights_management#show_water_rights', as: :show_water_rights
  get "/get-water-rights-data/:id(.:format)", to: "water_rights_management#get_data", as: :get_water_rights_data

  resources :water_rights
  resources :point_of_diversions
  resources :place_of_use_areas
  resources :for_sales
  resources :wanteds

  post '/place_of_use_area_water_rights(.:format)', to: 'place_of_use_area_water_rights#create', as: :place_of_use_area_water_rights
  delete '/place_of_use_area_water_rights(.:format)', to: 'place_of_use_area_water_rights#destroy', as: :place_of_use_area_water_right
  post '/point_of_diversion_water_rights(.:format)', to: 'point_of_diversion_water_rights#create', as: :point_of_diversion_water_rights
  delete '/point_of_diversion_water_rights(.:format)', to: 'point_of_diversion_water_rights#destroy', as: :point_of_diversion_water_right

  get "/listings-dashboard", to: "listings#dashboard", as: :listings_dashboard
  get "/buy-sell", to: "listings#buy_sell", as: :buy_sell
  get "/get-listings-data", to: "listings#get_data", as: :get_listings_data

  # get "/contact", to: "static_pages#contact", as: :contact

  resources :listing_areas

  devise_for :users

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="col-sm-7">
      <ul class="footer-nav">
        <li><%= link_to 'Profile', page_path('profile') %></li>
        <li><%= link_to 'Contact', page_path('contact') %></li>
        <li><%= link_to 'Buy/Sell', buy_sell_path %></li>
        <li><%= link_to 'Water Rights', show_water_rights_path %></li>
        <% unless user_signed_in? %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-sm-5 text-right">
      <span>Copyright 2023. Riley Water Consulting</span>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<div class="brand hidden-xs">
  <%= link_to (image_tag "LOGO_wheel.jpg", class: "logo"), root_path %>
</div>

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Riley Water Consulting', root_path, class: 'navbar-brand visible-xs' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <% if current_user.has_role? :admin %>
            <li><%= link_to 'Listings Dashboard', listings_dashboard_path %></li>
            <li><%= link_to 'WRM Dashboard', wrm_dashboard_path %></li>
            <li><%#= link_to 'Admin', users_path %></li>
          <% end %>
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
        <%#= link_to 'Login', new_user_session_path %>
        </ul>
      <% end %>
      
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Diligence Claims', page_path('diligence-claims') %></li>
            <li><%= link_to 'Proof of Beneficial Use', page_path('proof-of-beneficial-use') %></li>
            <li><%= link_to 'Change Application', page_path('change-application') %></li>
            <li><%= link_to 'Reports of Conveyance (Title)', page_path('reports-of-conveyance') %></li>
            <li><%= link_to '40 Year Plan', page_path('fourty-year-plan') %></li>
            <li><%= link_to 'Extension Request', page_path('extension-request') %></li>
            <li><%= link_to 'Declarations of Beneficial Use', page_path('declarations-of-beneficial-use') %></li>
            <li><%= link_to 'Applications to Appropriate', page_path('applications-to-appropriate') %></li>
            <li><%= link_to 'Non-use Application', page_path('non-use-application') %></li>
          </ul>
        </li>
        <li><%= link_to 'Profile', page_path('profile') %></li>
        <li><%= link_to 'Contact', page_path('contact') %></li>
        <li><%= link_to 'Buy/Sell', buy_sell_path %></li>
        <li><%= link_to 'Water Rights', show_water_rights_path %></li>
        <% unless user_signed_in? %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_other_services.html.erb
<div class="col-md-4">
  <div class="visible-xs-inline visible-sm-inline">
    <h4 class="service-list-header text-center">All Services</h4>
    <div class="list-group">
      <%= link_to "Diligence Claims", page_path('diligence-claims'), class: 'list-group-item text-center' %>
      <%= link_to 'Proof of Beneficial Use', page_path('proof-of-beneficial-use'), class: 'list-group-item text-center' %>
      <%= link_to 'Change Application', page_path('change-application'), class: 'list-group-item text-center' %>
      <%= link_to 'Reports of Conveyance (Title)', page_path('reports-of-conveyance'), class: 'list-group-item text-center' %>
      <%= link_to '40 Year Plan', page_path('fourty-year-plan'), class: 'list-group-item text-center' %>
      <%= link_to 'Extension Request', page_path('extension-request'), class: 'list-group-item text-center' %>
      <%= link_to 'Declarations of Beneficial Use', page_path('declarations-of-beneficial-use'), class: 'list-group-item text-center' %>
      <%= link_to 'Applications to Appropriate', page_path('applications-to-appropriate'), class: 'list-group-item text-center' %>
      <%= link_to 'Non-use Application', page_path('non-use-application'), class: 'list-group-item text-center' %>
    </div>
  </div>
  <div class="visible-md-inline visible-lg-inline">
    <h4 class="service-list-header text-center">All Services</h4>
    <div class="list-group">
      <%= link_to "Diligence Claims", page_path('diligence-claims'), class: 'list-group-item text-center' %>
      <%= link_to 'Proof of Beneficial Use', page_path('proof-of-beneficial-use'), class: 'list-group-item text-center' %>
      <%= link_to 'Change Application', page_path('change-application'), class: 'list-group-item text-center' %>
      <%= link_to 'Reports of Conveyance (Title)', page_path('reports-of-conveyance'), class: 'list-group-item text-center' %>
      <%= link_to '40 Year Plan', page_path('fourty-year-plan'), class: 'list-group-item text-center' %>
      <%= link_to 'Extension Request', page_path('extension-request'), class: 'list-group-item text-center' %>
      <%= link_to 'Declarations of Beneficial Use', page_path('declarations-of-beneficial-use'), class: 'list-group-item text-center' %>
      <%= link_to 'Applications to Appropriate', page_path('applications-to-appropriate'), class: 'list-group-item text-center' %>
      <%= link_to 'Non-use Application', page_path('non-use-application'), class: 'list-group-item text-center' %>
    </div>
  </div>
</div>

app/views/layouts/_services_page.html.erb
<div id="services-page" class="container">
  <div class="row text-center">
    <%= image_tag img_link, class: 'services-pic' %>
    <h1><%= title -%></h1>
  </div>
  <div class="row">
    <div class="col-md-8 col-lg-6 col-lg-offset-1">
      <%= yield %>
    </div>
    <%= render "layouts/other_services" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="ROBOTS" content="NOODP" />
  <title>Riley Water Consulting</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Quicksand:400,500|Roboto:100|Raleway:400,700" rel="stylesheet">
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= google_maps_api %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="<%= body_class %>">
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
<!--       <div class="container"> -->
        <%= render 'flashes' -%>
        <%= yield %>
        <%= render 'javascript' %>
      <!-- </div> -->
    </main>
    <div id="push"></div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>